### PR TITLE
Feature/fri 85 add component id to failure

### PR DESCRIPTION
**Pull request by QuyenLy87**
Hi @kaicode , @CoderMChu 
The component id can be added to most of the assertions. But some of them can not. Please have a look the following assertions and let me know if they require any changes:

component-centric-snapshot-expression-association-unique-mapTarget.sql
component-centric-snapshot-attribute-value-only-one-active-inactivation-reason.sql
component-centric-snapshot-ctv3-code-unique.sql
component-centric-snapshot-ctv3-ratio.sql
component-centric-snapshot-inferred-unique-per-concept.sql
component-centric-snapshot-no-duplicate-association-of-SEP.sql
component-centric-snapshot-referenced-refsetId-of-refeset-member-must-be-valid.sql
file-centric-snapshot-association-expression-valid-referencecomponentid.sql
file-centric-snapshot-association-valid-key.sql
file-centric-snapshot-map-correlation-origin-referencecomponentid.sql
file-centric-snapshot-simple-map-valid-key.sql
file-centric-snapshot-simple-refset-valid-key.sql
component-centric-snomed-ct-expression-validation-proc.sql

### CODE REVIEW

**Comment by kaicode** [comment]
Hi @QuyenLy87, when the assertion is validating a reference set, like a map or association, we should be able to use the refset member uuid as the component id? It looks like there is also a unique inferred relationship test there, in the case could multiple relationships ids be reported?

**Comment by QuyenLy87** [comment]
Yes, that's true. @kaicode  . I'm doing that way. However, if the assertion use some aggregating functions (example: group by), then we can not use the id as component id

**Review by CoderMChu — APPROVED** [review]
@QuyenLy87  It looks good. Thanks.

**Comment by kaicode** [comment]
@CoderMChu I don't think this is sufficient.

It would be a bad idea to whitelist the assertion `file-centric-snapshot-simple-refset-valid-key.sql` at the concept level because that would whitelist the concept under all reference sets. It should be possible to select the refset members even when using "group by" with the use of a subquery? 
I've built an example of how to do this to report the duplicate refset member ids when using group by across multiple fields - http://sqlfiddle.com/#!9/fbe6edd/1/0

**Comment by CoderMChu** [comment]
@kaicode Sorry I didn't leave a comment here but I have discussed with @QuyenLy87 about this. He is going to update these. He had mysql errors before due to mysql config:  "sql_mode=only_full_group_by". After removing this config it seems to be working for him now.

**Comment by QuyenLy87** [comment]
Hi @kaicode , @CoderMChu  all remaining assertions have been updated. Could you please review again? Thanks

**Comment by kaicode** [comment]
I've not reviewed the code but this sounds good to me. Will leave Michael to do final review. Thanks.

**Review by CoderMChu — COMMENTED** [review]
@QuyenLy87 It looks good. Can you please rebase and convert new assertions added from MDRS? Thanks.

**Pull request merged**
