### PR TITLE
SSO Integration

### PR DESCRIPTION
**Pull request by HM-huyle**
- nginx configuration must be updated
- Correct roles and users should be added to IMS
- After correct roles and users added, security.xml must be updated

### CODE REVIEW

**Comment by sherrif10** [comment]
Hey all am sharif from uganda software developer  and am interested in being part of this organisation and would like to start contribute to you code if am granted permission.Saw this way of committing and i felt frustrated, According to how open source commits code, they dont allow having many commits but its as if here you allow merging more than one commit into master branch , ??cc @coderMChu am happy to be here once again

**Comment by kaicode** [comment]
Hello @sherrif10, yes a pull request can contain multiple commits but it should be focused on a single feature. This pull request (#11) has fairly narrow scope but there is an unusually large number of commits. Pull requests typically contain between 1 and 10 commits where all the commits have a single focus of change.
We would welcome your contribution. Do you have anything specific you are thinking of working on?

**Comment by sherrif10** [comment]
Thanks @kaicode ,Am just imagining when a pushed commit need some changes to be fixed, then that would mean ,you will need to squash then of which this would require you some technical bit of  time

**Comment by sherrif10** [comment]
Yes @kaicode  i would like to contribute to reporting-ui module,  i and other modules , i hope by contributing , am learning new ways of solving problems and gain more experience. thanks. you can as well recommend me to issue tracker of your projects if possible sir.

**Pull request closed without merging**
